<?php

/** @see https://github.com/mailpace/templates/blob/main/dist/security_alert.html */

/** @noinspection PhpUndefinedVariableInspection */

declare(strict_types=1);

// phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
// phpcs:disable Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore
// phpcs:disable Generic.Files.InlineHTML.Found

use BuzzingPixel\Templating\TemplateEngine;
use MissionControlUrlMonitoring\MonitoredUrls\Incidents\MonitoredUrlIncident;
use MissionControlUrlMonitoring\MonitoredUrls\MonitoredUrl;

/** @phpstan-ignore-next-line */
assert($this instanceof TemplateEngine);

/** @phpstan-ignore-next-line */
assert(is_string($title));

/** @phpstan-ignore-next-line */
assert($url instanceof MonitoredUrl);

/** @phpstan-ignore-next-line */
assert($incident instanceof MonitoredUrlIncident);

/** @phpstan-ignore-next-line */
assert(is_string($viewIncidentsUrl));

?>

<!DOCTYPE html>
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml">
<head>
    <meta charset="utf-8">
    <meta name="x-apple-disable-message-reformatting">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="format-detection" content="telephone=no, date=no, address=no, email=no">
    <meta http-equiv="Content-Type" content="text/html charset=UTF-8">
    <meta name="color-scheme" content="light dark">
    <meta name="supported-color-schemes" content="light dark">
    <!--[if mso]>
    <noscript>
        <xml>
            <o:OfficeDocumentSettings
                xmlns:o="urn:schemas-microsoft-com:office:office"
            >
                <o:PixelsPerInch>96</o:PixelsPerInch>
            </o:OfficeDocumentSettings>
        </xml>
    </noscript>
    <style>
        td,
        th,
        div,
        p,
        a,
        h1,
        h2,
        h3,
        h4,
        h5,
        h6 {
            font-family: "Segoe UI", sans-serif;
            mso-line-height-rule: exactly;
        }
    </style>
    <![endif]-->
    <title><?=$title?></title>
    <style>:root {
            color-scheme: light dark;
            supported-color-schemes: light dark;
        }</style>
    <style>
        .hover-bg-blue-600:hover {
            background-color: #06B6D4 !important;
        }
        .hover-underline:hover {
            text-decoration: underline !important;
        }
        @media (max-width: 600px) {
            .sm-w-full {
                width: 100% !important;
            }
            .sm-py-32 {
                padding-top: 32px !important;
                padding-bottom: 32px !important;
            }
            .sm-px-24 {
                padding-left: 24px !important;
                padding-right: 24px !important;
            }
            .sm-leading-32 {
                line-height: 32px !important;
            }
        }
        @media (prefers-color-scheme: dark) {
            .dark-mode-bg-gray-999 {
                background-color: #1b1c1e !important;
            }
            .dark-mode-bg-gray-989 {
                background-color: #2d2d2d !important;
            }
            .dark-mode-text-gray-979 {
                color: #a9a9a9 !important;
            }
            .dark-mode-text-white {
                color: #ffffff !important;
            }
        }
    </style>
</head>
<body class="dark-mode-bg-gray-999" style="margin: 0; width: 100%; padding: 0; word-break: break-word; -webkit-font-smoothing: antialiased; background-color: #f3f4f6;">
<div style="display: none;">
    We've noticed a new sign-in to your account&#847; &#847; &#847; &#847; &#847; &#847; &#847;
    &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847;
    &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847;
    &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847;
    &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847;
    &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &zwnj;
    &#160;&#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847;
    &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847;
    &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847;
    &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847;
    &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847;
    &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &zwnj;
    &#160;&#847; &#847; &#847; &#847; &#847;
</div>
<div role="article" aria-roledescription="email" aria-label="New sign-in to your account" lang="en" style="padding-top: 20px; padding-bottom: 20px;">
    <table style="width: 100%; font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', sans-serif;" cellpadding="0" cellspacing="0" role="presentation">
        <tr>
            <td align="center" class="dark-mode-bg-gray-999" style="background-color: #f3f4f6;">
                <table class="sm-w-full" style="width: 600px;" cellpadding="0" cellspacing="0" role="presentation">
                    <tr>
                        <td align="center" class="sm-px-24">
                            <table style="margin-bottom: 48px; width: 100%;" cellpadding="0" cellspacing="0" role="presentation">
                                <tr>
                                    <td class="dark-mode-bg-gray-989 dark-mode-text-gray-979 sm-px-24" style="background-color: #ffffff; padding: 48px; text-align: left; font-size: 16px; line-height: 24px; color: #1f2937;">
                                        <p class="sm-leading-32 dark-mode-text-white" style="margin: 0; margin-bottom: 36px; font-family: ui-serif, Georgia, Cambria, 'Times New Roman', Times, serif; font-size: 24px; font-weight: 600; color: #000000; line-height: 36px;">
                                            <?=$title?>
                                        </p>
                                        <table style="margin-bottom: 24px;" cellpadding="0" cellspacing="0" role="presentation">
                                            <tr>
                                                <td width="20" align="center" valign="top">&bull;</td>
                                                <td><strong>URL Title</strong>: <?=$url->title->toNative()?></td>
                                            </tr>
                                            <tr>
                                                <td width="20" align="center" valign="top">&bull;</td>
                                                <td><strong>URL</strong>: <a href="<?=$url->url->toNative()?>" class="hover-underline" style="color: #0891B2; text-decoration: none;"><?=$url->url->toNative()?></a></td>
                                            </tr>
                                            <tr>
                                                <td width="20" align="center" valign="top">&bull;</td>
                                                <td><strong>Status Code</strong>: <?=$incident->statusCode->toNative()?></td>
                                            </tr>
                                            <tr>
                                                <td width="20" align="center" valign="top">&bull;</td>
                                                <td><strong>Message</strong>: <?=$incident->message->toNative()?></td>
                                            </tr>
                                        </table>
                                        <a href="<?=$viewIncidentsUrl?>" class="hover-bg-blue-600" style="display: inline-block; background-color: #0891B2; padding-left: 14px; padding-right: 14px; padding-top: 8px; padding-bottom: 8px; text-align: center; font-size: 16px; font-weight: 600; text-transform: uppercase; color: #ffffff; text-decoration: none; margin-bottom: 8px; margin-right: 8px;">
                                            <!--[if mso
                                              ]><i
                                                style="
                                                  letter-spacing: 24px;
                                                  mso-font-width: -100%;
                                                  mso-text-raise: 30px;
                                                "
                                                >&#8202;</i><!
                                            [endif]-->
                                            <span style="mso-text-raise: 16px">View Incidents</span>
                                            <!--[if mso
                                              ]><i style="letter-spacing: 24px; mso-font-width: -100%">&#8202;</i><!
                                            [endif]-->
                                        </a>
                                        <a href="<?=$url->url->toNative()?>" class="hover-bg-blue-600" style="display: inline-block; background-color: #0891B2; padding-left: 14px; padding-right: 14px; padding-top: 8px; padding-bottom: 8px; text-align: center; font-size: 16px; font-weight: 600; text-transform: uppercase; color: #ffffff; text-decoration: none; margin-bottom: 8px;">
                                            <!--[if mso
                                              ]><i
                                                style="
                                                  letter-spacing: 24px;
                                                  mso-font-width: -100%;
                                                  mso-text-raise: 30px;
                                                "
                                                >&#8202;</i><!
                                            [endif]-->
                                            <span style="mso-text-raise: 16px">Go To URL</span>
                                            <!--[if mso
                                              ]><i style="letter-spacing: 24px; mso-font-width: -100%">&#8202;</i><!
                                            [endif]-->
                                        </a>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
</body>
</html>
